### ISSUE TITLE
코드 사용 문의 드립니다.

### ISSUE THREAD

**Issue by blackbbean** [Cube219/BPP_RandomChat_Server#1]
안녕하세요.
저는 동국대학교 컴퓨터 공학과에 재학중인 학생입니다.
학교에서 오픈소스를 활용한 랜덤 채팅 프로그램 제작 프로젝트를 하게되어서 깃허브에서 
프로젝트를 찾아보던 중, Cube219님의 소스를 발견하게 되었습니다.
사용하고 싶지만, 따로 라이센스 표기가 되어있지 않아 이렇게 issue를 올리게 되었습니다.
혹시  이 프로젝트의 코드를(서버+클라이언트) QT환경에서 소스를 변형에서 사용해도 되는지 허락을 맡고 싶습니다.
답변 기다릴게요 :)

**Comment by Cube219** [comment]
네 안녕하세요!
이 글을 늦게 봤네요ㅜㅜ
네 소스코드 가져다가 쓰셔도 됩니다.
그리고 차후에 라이센스 넣도록 하겠습니다.
